# Generated by Django 5.2.17 on 2026-09-09 19:28

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('caixa_email', models.EmailField(max_length=254, unique=True)),
                ('setores', models.JSONField(default=list)),
                ('retencao_dias', models.PositiveIntegerField(default=1825)),
                ('proximo_numero', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('assunto', models.CharField(max_length=500)),
                ('cliente_nome', models.CharField(blank=True, max_length=200)),
                ('cliente_email', models.EmailField(blank=True, max_length=254)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('arquivado_em', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamados', to='core.empresa')),
            ],
            options={
                'verbose_name': 'chamado',
                'verbose_name_plural': 'chamados',
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField()),
                ('remetente', models.CharField(blank=True, max_length=320)),
                ('destinatario', models.CharField(blank=True, max_length=320)),
                ('assunto', models.CharField(blank=True, max_length=500)),
                ('recebido_em', models.DateTimeField()),
                ('bruto', models.BinaryField()),
                ('texto', models.TextField()),
                ('norm_v', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('citacao_offset', models.IntegerField(blank=True, null=True)),
                ('message_id', models.CharField(blank=True, max_length=998)),
                ('search', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='core.chamado')),
            ],
            options={
                'verbose_name': 'mensagem',
                'verbose_name_plural': 'mensagens',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('mime', models.CharField(max_length=180)),
                ('arquivo', models.FileField(upload_to='anexos/%Y/%m/')),
                ('sha256', models.CharField(max_length=64)),
                ('mensagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='core.mensagem')),
            ],
            options={
                'verbose_name': 'anexo',
                'verbose_name_plural': 'anexos',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('setor', models.CharField(max_length=80)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='core.empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pessoa',
                'verbose_name_plural': 'pessoas',
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=80)),
                ('texto', models.TextField()),
                ('situacao', models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluido', 'Concluído'), ('bloqueado', 'Bloqueado'), ('duvida_cliente', 'Dúvida com o cliente')], max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(blank=True, null=True)),
                ('search', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.pessoa')),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='core.chamado')),
                ('versao_anterior', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versao_seguinte', to='core.registro')),
            ],
            options={
                'verbose_name': 'registro',
                'verbose_name_plural': 'registros',
                'ordering': ['criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='chamado',
            index=models.Index(fields=['empresa', '-criado_em'], name='core_chamad_empresa_9a26cd_idx'),
        ),
        migrations.AddConstraint(
            model_name='chamado',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uniq_codigo_empresa'),
        ),
        migrations.AddIndex(
            model_name='mensagem',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search'], name='core_mensag_search_50a601_gin'),
        ),
        migrations.AddConstraint(
            model_name='mensagem',
            constraint=models.UniqueConstraint(fields=('chamado', 'ordem'), name='uniq_ordem_chamado'),
        ),
        migrations.AddConstraint(
            model_name='mensagem',
            constraint=models.UniqueConstraint(condition=models.Q(('message_id', ''), _negated=True), fields=('chamado', 'message_id'), name='uniq_msgid_chamado'),
        ),
        migrations.AddIndex(
            model_name='registro',
            index=models.Index(fields=['chamado', 'criado_em'], name='core_regist_chamado_25177a_idx'),
        ),
        migrations.AddIndex(
            model_name='registro',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search'], name='core_regist_search_66fb02_gin'),
        ),
    ]
