# Generated by Django 5.2.17 on 2026-09-09 23:48

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecebido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=998)),
                ('recebido_em', models.DateTimeField()),
                ('lido_em', models.DateTimeField(auto_now_add=True)),
                ('remetente_nome', models.CharField(blank=True, max_length=200)),
                ('remetente_email', models.CharField(max_length=320)),
                ('destinatario', models.CharField(blank=True, max_length=320)),
                ('assunto', models.CharField(blank=True, max_length=500)),
                ('refs', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('bruto', models.BinaryField()),
                ('texto', models.TextField()),
                ('norm_v', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('citacao_offset', models.IntegerField(blank=True, null=True)),
                ('situacao', models.CharField(choices=[('pendente', 'Pendente'), ('promovido', 'Promovido a chamado'), ('descartado', 'Descartado')], default='pendente', max_length=20)),
                ('promovido_em', models.DateTimeField(blank=True, null=True)),
                ('descartado_em', models.DateTimeField(blank=True, null=True)),
                ('chamado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_recebidos', to='core.chamado')),
                ('descartado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emails_descartados', to='core.pessoa')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='core.empresa')),
                ('promovido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emails_promovidos', to='core.pessoa')),
            ],
            options={
                'verbose_name': 'e-mail recebido',
                'verbose_name_plural': 'e-mails recebidos',
                'ordering': ['-recebido_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AnexoRecebido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('mime', models.CharField(max_length=180)),
                ('arquivo', models.FileField(upload_to='recebidos/%Y/%m/')),
                ('sha256', models.CharField(max_length=64)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='core.emailrecebido')),
            ],
            options={
                'verbose_name': 'anexo recebido',
                'verbose_name_plural': 'anexos recebidos',
            },
        ),
        migrations.AddIndex(
            model_name='emailrecebido',
            index=models.Index(fields=['empresa', 'situacao', '-recebido_em'], name='core_emailr_empresa_2c1b94_idx'),
        ),
        migrations.AddConstraint(
            model_name='emailrecebido',
            constraint=models.UniqueConstraint(fields=('empresa', 'message_id'), name='uniq_msgid_empresa'),
        ),
    ]
