# Generated by Django 5.2.17 on 2026-09-10 00:32

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emailrecebido_anexorecebido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=core.models.token_de_convite, max_length=64, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('setor', models.CharField(blank=True, max_length=80)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField(default=core.models.prazo_de_convite)),
                ('usado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'convite',
                'verbose_name_plural': 'convites',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='pessoa',
            name='papel',
            field=models.CharField(choices=[('admin', 'Administrador'), ('membro', 'Membro')], default='membro', max_length=10),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='caixa_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddConstraint(
            model_name='empresa',
            constraint=models.UniqueConstraint(condition=models.Q(('caixa_email', ''), _negated=True), fields=('caixa_email',), name='uniq_caixa_email'),
        ),
        migrations.AddField(
            model_name='convite',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='convites_feitos', to='core.pessoa'),
        ),
        migrations.AddField(
            model_name='convite',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='convite',
            name='usado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convites_aceitos', to='core.pessoa'),
        ),
        migrations.AddIndex(
            model_name='convite',
            index=models.Index(fields=['empresa', '-criado_em'], name='core_convit_empresa_ba7e88_idx'),
        ),
    ]
