# Generated by Django 5.2.17 on 2026-09-10 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preencher_criador(apps, schema_editor):
    Empresa = apps.get_model("core", "Empresa")
    Pessoa = apps.get_model("core", "Pessoa")
    for empresa in Empresa.objects.all().iterator():
        # O cadastro antigo criava o primeiro administrador da empresa.
        pessoa = Pessoa.objects.filter(empresa_id=empresa.pk, papel="admin").order_by("pk").first()
        if pessoa:
            Empresa.objects.filter(pk=empresa.pk).update(criador_id=pessoa.user_id)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_convite_pessoa_papel_alter_empresa_caixa_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='criador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresa',
            name='imap_host',
            field=models.CharField(blank=True, default='', max_length=253),
        ),
        migrations.AddField(
            model_name='empresa',
            name='imap_pasta',
            field=models.CharField(default='INBOX', max_length=255),
        ),
        migrations.AddField(
            model_name='empresa',
            name='imap_senha',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='empresa',
            name='imap_usuario',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.RunPython(preencher_criador, migrations.RunPython.noop),
    ]
